#import <Foundation/Foundation.h>
#import "OAIBalance.h"
#import "OAIError.h"
#import "OAIApi.h"

/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIBalanceApi: NSObject <OAIApi>

extern NSString* kOAIBalanceApiErrorDomain;
extern NSInteger kOAIBalanceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// The Balance API provides a count of request credits left in the user's account for the day. Balance is reset at midnight UTC everyday (00:00 UTC).
///
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"The request has been made from an unauthorized domain.",
///  code:404 message:"No location or places were found for the given input",
///  code:429 message:"Request exceeded the rate-limits set on your account",
///  code:500 message:"Internal Server Error"
///
/// @return OAIBalance*
-(NSURLSessionTask*) balanceWithCompletionHandler: 
    (void (^)(OAIBalance* output, NSError* error)) handler;



@end
