#import <Foundation/Foundation.h>
#import "OAIDirectionsMatching.h"
#import "OAIError.h"
#import "OAIApi.h"

/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIMatchingApi: NSObject <OAIApi>

extern NSString* kOAIMatchingApiErrorDomain;
extern NSInteger kOAIMatchingApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Matching Service
/// Matching API matches or snaps given GPS points to the road network in the most plausible way.  Please note the request might result multiple sub-traces.  Large jumps in the timestamps (> 60s) or improbable transitions lead to trace splits if a complete matching could not be found. The algorithm might not be able to match all points. Outliers are removed if they can not be matched successfully.
///
/// @param coordinates String of format {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline}) or polyline6({polyline6}). polyline follows Google&#39;s polyline format with precision 5
/// @param generateHints Adds a Hint to the response which can be used in subsequent requests, see hints parameter. Input Value - true (default), false Format - Base64 String (optional)
/// @param approaches Keep waypoints on curb side. Input Value - {approach};{approach}[;{approach} ...] Format - curb or unrestricted (default) (optional)
/// @param exclude Additive list of classes to avoid, order does not matter. input Value - {class}[,{class}] Format - A class name determined by the profile or none. (optional)
/// @param bearings Limits the search to segments with given bearing in degrees towards true north in clockwise direction. List of positive integer pairs separated by semi-colon and bearings array should be equal to length of coordinate array. Input Value :- {bearing};{bearing}[;{bearing} ...] Bearing follows the following format : bearing {value},{range} integer 0 .. 360,integer 0 .. 180 (optional)
/// @param radiuses Limits the search to given radius in meters Radiuses array length should be same as coordinates array, eaach value separated by semi-colon. Input Value - {radius};{radius}[;{radius} ...] Radius has following format :- double &gt;&#x3D; 0 or unlimited (default) (optional)
/// @param steps Returned route steps for each route leg [ true, false (default) ] (optional)
/// @param annotations Returns additional metadata for each coordinate along the route geometry.  [ true, false (default), nodes, distance, duration, datasources, weight, speed ] (optional) (default to @""false"")
/// @param geometries Returned route geometry format (influences overview and per step) [ polyline (default), polyline6, geojson ] (optional) (default to @""polyline"")
/// @param overview Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all. [ simplified (default), full, false ] (optional) (default to @""simplified"")
/// @param timestamps Timestamps for the input locations in seconds since UNIX epoch. Timestamps need to be monotonically increasing. [ {timestamp};{timestamp}[;{timestamp} ...]  integer seconds since UNIX epoch (optional)
/// @param gaps Allows the input track splitting based on huge timestamp gaps between points. [ split (default), ignore ] (optional) (default to @""split"")
/// @param tidy Allows the input track modification to obtain better matching quality for noisy tracks. [ true, false (default) ] (optional) (default to @""false"")
/// @param waypoints Treats input coordinates indicated by given indices as waypoints in returned Match object. Default is to treat all input coordinates as waypoints. [ {index};{index};{index}... ] (optional)
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"The request has been made from an unauthorized domain.",
///  code:404 message:"No location or places were found for the given input",
///  code:429 message:"Request exceeded the rate-limits set on your account",
///  code:500 message:"Internal Server Error"
///
/// @return OAIDirectionsMatching*
-(NSURLSessionTask*) matchingWithCoordinates: (NSString*) coordinates
    generateHints: (NSString*) generateHints
    approaches: (NSString*) approaches
    exclude: (NSString*) exclude
    bearings: (NSString*) bearings
    radiuses: (NSString*) radiuses
    steps: (NSString*) steps
    annotations: (NSString*) annotations
    geometries: (NSString*) geometries
    overview: (NSString*) overview
    timestamps: (NSString*) timestamps
    gaps: (NSString*) gaps
    tidy: (NSString*) tidy
    waypoints: (NSString*) waypoints
    completionHandler: (void (^)(OAIDirectionsMatching* output, NSError* error)) handler;



@end
