#import <Foundation/Foundation.h>
#import "OAIError.h"
#import "OAILocation.h"
#import "OAIApi.h"

/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIReverseApi: NSObject <OAIApi>

extern NSString* kOAIReverseApiErrorDomain;
extern NSInteger kOAIReverseApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Reverse Geocoding
/// Reverse geocoding is the process of converting a coordinate or location (latitude, longitude) to a readable address or place name. This permits the identification of nearby street addresses, places, and/or area subdivisions such as a neighborhood, county, state, or country.
///
/// @param lat Latitude of the location to generate an address for.
/// @param lon Longitude of the location to generate an address for.
/// @param format Format to geocode. Only JSON supported for SDKs
/// @param normalizecity Normalizes village to city level data to city
/// @param addressdetails Include a breakdown of the address into elements. Defaults to 1. (optional) (default to @1)
/// @param acceptLanguage Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Defaults to en. To use native language for the response when available, use accept-language&#x3D;native (optional)
/// @param namedetails Include a list of alternative names in the results. These may include language variants, references, operator and brand. (optional)
/// @param extratags Include additional information in the result if available, e.g. wikipedia link, opening hours. (optional)
/// @param statecode Adds state or province code when available to the statecode key inside the address element. Currently supported for addresses in the USA, Canada and Australia. Defaults to 0 (optional)
/// @param showdistance Returns the straight line distance (meters) between the input location and the result&#39;s location. Value is set in the distance key of the response. Defaults to 0 [0,1] (optional)
/// @param postaladdress Returns address inside the postaladdress key, that is specifically formatted for each country. Currently supported for addresses in Germany. Defaults to 0 [0,1] (optional)
/// 
///  code:200 message:"OK",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:403 message:"The request has been made from an unauthorized domain.",
///  code:404 message:"No location or places were found for the given input",
///  code:429 message:"Request exceeded the rate-limits set on your account",
///  code:500 message:"Internal Server Error"
///
/// @return OAILocation*
-(NSURLSessionTask*) reverseWithLat: (NSNumber*) lat
    lon: (NSNumber*) lon
    format: (NSString*) format
    normalizecity: (NSNumber*) normalizecity
    addressdetails: (NSNumber*) addressdetails
    acceptLanguage: (NSString*) acceptLanguage
    namedetails: (NSNumber*) namedetails
    extratags: (NSNumber*) extratags
    statecode: (NSNumber*) statecode
    showdistance: (NSNumber*) showdistance
    postaladdress: (NSNumber*) postaladdress
    completionHandler: (void (^)(OAILocation* output, NSError* error)) handler;



@end
