#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIAddress.h"
#import "OAIMatchquality.h"
#import "OAINamedetails.h"
@protocol OAIAddress;
@class OAIAddress;
@protocol OAIMatchquality;
@class OAIMatchquality;
@protocol OAINamedetails;
@class OAINamedetails;



@protocol OAILocation
@end

@interface OAILocation : OAIObject


@property(nonatomic) NSNumber* distance;

@property(nonatomic) NSString* placeId;

@property(nonatomic) NSString* licence;

@property(nonatomic) NSString* osmType;

@property(nonatomic) NSString* osmId;

@property(nonatomic) NSArray<NSString*>* boundingbox;

@property(nonatomic) NSString* lat;

@property(nonatomic) NSString* lon;

@property(nonatomic) NSString* displayName;

@property(nonatomic) NSString* _class;

@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* importance;

@property(nonatomic) OAIAddress* address;

@property(nonatomic) OAINamedetails* namedetails;

@property(nonatomic) OAIMatchquality* matchquality;

@end
