#import <Foundation/Foundation.h>
#import "OAIError.h"
#import "OAILocation.h"
#import "OAIApi.h"

/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* OpenAPI spec version: 1.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIReverseApi: NSObject <OAIApi>

extern NSString* kOAIReverseApiErrorDomain;
extern NSInteger kOAIReverseApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Reverse Geocoding
/// Reverse geocoding is the process of converting a coordinate or location (latitude, longitude) to a readable address or place name. This permits the identification of nearby street addresses, places, and/or area subdivisions such as a neighborhood, county, state, or country.
///
/// @param lat Latitude of the location to generate an address for.
/// @param lon Longitude of the location to generate an address for.
/// @param format Format to geocode. Only JSON supported for SDKs
/// @param normalizecity Normalizes village to city level data to city
/// @param addressdetails Include a breakdown of the address into elements. Defaults to 1. (optional) (default to @1)
/// @param acceptLanguage Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Defaults to en. To use native language for the response when available, use accept-language&#x3D;native (optional)
/// @param namedetails Include a list of alternative names in the results. These may include language variants, references, operator and brand. (optional)
/// @param extratags Include additional information in the result if available, e.g. wikipedia link, opening hours. (optional)
/// 
///  code:200 message:"OK",
///  code:400 message:"Required parameters are missing, or invalid",
///  code:401 message:"An invalid API key was provided / Key not active",
///  code:404 message:"No location or places were found for the given input",
///  code:429 message:"Too Many Requests",
///  code:500 message:"Unknown error - Please try again after some time"
///
/// @return OAILocation*
-(NSURLSessionTask*) reverseWithLat: (NSNumber*) lat
    lon: (NSNumber*) lon
    format: (NSString*) format
    normalizecity: (NSNumber*) normalizecity
    addressdetails: (NSNumber*) addressdetails
    acceptLanguage: (NSString*) acceptLanguage
    namedetails: (NSNumber*) namedetails
    extratags: (NSNumber*) extratags
    completionHandler: (void (^)(OAILocation* output, NSError* error)) handler;



@end
